### ISSUE TITLE
Flaming octocat spotted in the wild

### ISSUE THREAD

**Issue by Pustur** [dhilipsiva/octodex#2]
Hey, 

thanks for making this website, I didn't know there were so many different octocats around 😄

As a reward for participating in hacktoberfest 2020, someone received this sticker:

<img width="872" alt="Flaming octocat" src="https://user-images.githubusercontent.com/13663338/103817088-55205280-5066-11eb-8926-a6b7edacf949.png">

([Original image](https://i.redd.it/91ykr4uqsa961.jpg))

Do you have any idea where to find the original artwork? Would be cool to add it to the site if we find it.

**Comment by dhilipsiva** [comment]
I guess that is octodex.github.com,if I am not wrong.
